### ISSUE TITLE
For practically reasons it maybe best to do this sort of thing using multi-threading on the CPU

### ISSUE THREAD

**Issue by JulianDicken** [Scrawk/Marching-Cubes-On-The-GPU#2]
I know this is old but you mention this in your readme, why is that so ? I am fairly new to compute shaders and have no idea why this is the case.

**Comment by Scrawk** [comment]
Doing anything in a compute shader means that the data you are operating on must exists in the GPU memory. This is fine if your only goal is to render the object but most of the time you would want to perform further operations on the results that maybe difficult or impossible to implement on the GPU, for example generating a collider for collisions.

This means you would be required to read the data back from the GPU memory. This can be a slow process that can negate any benefit of doing the operation on the GPU in the first place. Modern GPU's are a lot faster at this than they use to be and async methods are available so it may not be such a issue.

 It depends a lot on the minimum shader model you are willing to support and how the GPUs driver is implemented. In some cases even a small read back can case a large stall as the driver will flush the GPU pipeline and stop whats its doing just to send your data back.

**Comment by stuw-u** [comment]
Just a random note here, if you're worried about not having the mesh on the cpu for collision, you should consider collision with the volumetric data itself. That's what Nel used for [Meor](https://store.steampowered.com/app/1319310/Meor/) and it works pretty well.
